// This file was automatically generated by build.rs
#![allow(unused_variables)]

#[naked]
#[inline(never)]
pub extern "C" fn malloc(size: usize) -> *mut u8 {
    let ret: *mut u8;
    unsafe {
        asm!("li $9, 0x33
              j 0xA0",
               lateout("$2") ret);
    }
    ret
}

#[naked]
#[inline(never)]
pub extern "C" fn free(buf: *mut u8) {
    unsafe {
        asm!("li $9, 0x34
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn calloc(sizex: usize, sizey: usize) -> *const u8 {
    let ret: *const u8;
    unsafe {
        asm!("li $9, 0x37
              j 0xA0",
               lateout("$2") ret);
    }
    ret
}

#[naked]
#[inline(never)]
pub extern "C" fn realloc(old_buf: *const u8, new_size: usize) {
    unsafe {
        asm!("li $9, 0x38
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn init_heap(addr: usize, size: usize) {
    unsafe {
        asm!("li $9, 0x39
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn printf(s: *const u8, v: u32) {
    unsafe {
        asm!("li $9, 0x3F
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn gpu_send_dma(xdst: u16, ydst: u16, xsiz: u16, ysize: u16, src: u32) {
    unsafe {
        asm!("li $9, 0x47
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn gpu_gp1_command_word(cmd: u32) {
    unsafe {
        asm!("li $9, 0x48
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn gpu_command_word(cmd: u32) {
    unsafe {
        asm!("li $9, 0x49
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn gpu_command_word_params(src: *const u32, num: usize) {
    unsafe {
        asm!("li $9, 0x4A
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn gpu_get_status() -> u32 {
    let ret: u32;
    unsafe {
        asm!("li $9, 0x4D
              j 0xA0",
               lateout("$2") ret);
    }
    ret
}

#[naked]
#[inline(never)]
pub extern "C" fn file_open(filename: *const u8, accessmode: u32) -> u8 {
    let ret: u8;
    unsafe {
        asm!("li $9, 0x00
              j 0xA0",
               lateout("$2") ret);
    }
    ret
}

#[naked]
#[inline(never)]
pub extern "C" fn load_exe_header(filename: *const u8, headerbuf: *mut u8) {
    unsafe {
        asm!("li $9, 0x41
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn load_exe_file(filename: *const u8, headerbuf: *mut u8) {
    unsafe {
        asm!("li $9, 0x42
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn do_execute(headerbuf: *mut u8, param1: u32, param2: u32) {
    unsafe {
        asm!("li $9, 0x43
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn load_and_execute(filename: *const u8, stackbase: u32, stackoffset: u32) {
    unsafe {
        asm!("li $9, 0x51
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn flush_cache() {
    unsafe {
        asm!("li $9, 0x44
              j 0xA0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn init_pad(buf1: *mut u8, siz1: usize, buf2: *mut u8, siz2: usize) {
    unsafe {
        asm!("li $9, 0x12
              j 0xB0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn start_pad() {
    unsafe {
        asm!("li $9, 0x13
              j 0xB0",
               lateout("$2") _);
    }
}

#[naked]
#[inline(never)]
pub extern "C" fn stop_pad() {
    unsafe {
        asm!("li $9, 0x14
              j 0xB0",
               lateout("$2") _);
    }
}
