// This file was automatically generated by build.rs
.set noreorder

.globl file_open
file_open:
    j 0xA0
    li $9, 0x00

.globl exit
exit:
    j 0xA0
    li $9, 0x06

.globl save_state
save_state:
    j 0xA0
    li $9, 0x13

.globl restore_state
restore_state:
    j 0xA0
    li $9, 0x14

.globl rand
rand:
    j 0xA0
    li $9, 0x2F

.globl srand
srand:
    j 0xA0
    li $9, 0x30

.globl malloc
malloc:
    j 0xA0
    li $9, 0x33

.globl free
free:
    j 0xA0
    li $9, 0x34

.globl calloc
calloc:
    j 0xA0
    li $9, 0x37

.globl realloc
realloc:
    j 0xA0
    li $9, 0x38

.globl init_heap
init_heap:
    j 0xA0
    li $9, 0x39

.globl system_error_exit
system_error_exit:
    j 0xA0
    li $9, 0x3A

.globl printf
printf:
    j 0xA0
    li $9, 0x3F

.globl load_exe_header
load_exe_header:
    j 0xA0
    li $9, 0x41

.globl load_exe_file
load_exe_file:
    j 0xA0
    li $9, 0x42

.globl do_execute
do_execute:
    j 0xA0
    li $9, 0x43

.globl flush_cache
flush_cache:
    j 0xA0
    li $9, 0x44

.globl gpu_send_dma
gpu_send_dma:
    j 0xA0
    li $9, 0x47

.globl gp1_command
gp1_command:
    j 0xA0
    li $9, 0x48

.globl gp0_command
gp0_command:
    j 0xA0
    li $9, 0x49

.globl gp0_command_params
gp0_command_params:
    j 0xA0
    li $9, 0x4A

.globl gpu_get_status
gpu_get_status:
    j 0xA0
    li $9, 0x4D

.globl gpu_sync
gpu_sync:
    j 0xA0
    li $9, 0x4E

.globl load_and_execute
load_and_execute:
    j 0xA0
    li $9, 0x51

.globl cd_init
cd_init:
    j 0xA0
    li $9, 0x54

.globl cd_remove
cd_remove:
    j 0xA0
    li $9, 0x56

.globl cd_async_get_status
cd_async_get_status:
    j 0xA0
    li $9, 0x7C

.globl add_cdrom_device
add_cdrom_device:
    j 0xA0
    li $9, 0x96

.globl set_memsize
set_memsize:
    j 0xA0
    li $9, 0x9F

.globl warm_boot
warm_boot:
    j 0xA0
    li $9, 0xA0

.globl cd_get_lbn
cd_get_lbn:
    j 0xA0
    li $9, 0xA4

.globl cd_get_status
cd_get_status:
    j 0xA0
    li $9, 0xA6

.globl get_system_info
get_system_info:
    j 0xA0
    li $9, 0xB4

.globl get_timer
get_timer:
    j 0xB0
    li $9, 0x03

.globl enable_timer_irq
enable_timer_irq:
    j 0xB0
    li $9, 0x04

.globl disable_timer_irq
disable_timer_irq:
    j 0xB0
    li $9, 0x05

.globl restart_timer
restart_timer:
    j 0xB0
    li $9, 0x06

.globl init_pad
init_pad:
    j 0xB0
    li $9, 0x12

.globl start_pad
start_pad:
    j 0xB0
    li $9, 0x13

.globl stop_pad
stop_pad:
    j 0xB0
    li $9, 0x14

.globl change_clear_pad
change_clear_pad:
    j 0xB0
    li $9, 0x5B

.globl change_clear_rcnt
change_clear_rcnt:
    j 0xC0
    li $9, 0x0A

.globl flush_std_in_out_put
flush_std_in_out_put:
    j 0xC0
    li $9, 0x13

.globl enter_critical_section
enter_critical_section:
    li $4, 0x01
    syscall 0x0
    jr $ra
    nop

.globl exit_critical_section
exit_critical_section:
    li $4, 0x02
    syscall 0x0
    jr $ra
    nop
