[package]
name = "bios"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psx = { path = "../../psx" }
bytemuck = "1.12.3"
linked_list_allocator = { version = "0.10.4", default-features = false, features = ["const_mut_refs"] }
