name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Provision build environment
      run: |
        rustup update nightly
        rustup component add rust-src --toolchain nightly
        # Install cargo-psx
        pushd cargo-psx
        cargo install --path .
        popd
        # Install the emulator, BFD linker and xvfb
        sudo apt-get install -y       \
            binutils-mipsel-linux-gnu \
            mednafen                  \
            xvfb
    - name: Build the BIOS
      run: |
        # Build the BIOS and configure the emulator to use it
        pushd examples/bios
        cargo psx build --link bios.ld
        mkdir -p ~/.mednafen/firmware
        cp target/mipsel-sony-psx/release/bios.exe \
            ~/.mednafen/firmware/scph7001.bin
        popd
    - name: Run the BIOS
      run: |
        # TODO: Add support for loading exes in the BIOS. This currently only runs the BIOS main
        # loop, but mednafen requires an executable so it just uses stdout for now.
        # TODO: The reference stdout for examples should be checked into the repo, not here
        pushd examples/stdout
        cargo psx build
        xvfb-run mednafen                                                                          \
            -psx.dbg_level 2                                                                       \
            -psx.bios_jp scph7001.bin                                                              \
            ~/work/psx-sdk-rs/psx-sdk-rs/examples/stdout/target/mipsel-sony-psx/release/stdout.exe \
            | tee bios_stdout &
        sleep 15
        grep "Starting main BIOS loop" bios_stdout
