name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Provision build environment
      run: |
        rustup update nightly
        rustup component add rust-src --toolchain nightly
        # Install cargo-psx
        pushd cargo-psx
        cargo install --path .
        popd
        # Install emulator
        sudo apt-get install -y mednafen
    - name: Build
      run: |
        pushd psx
        # Check that library builds
        cargo psx build
        popd
        # Check that BIOS builds
        pushd examples/bios
        cargo psx build --link bios.ld
        popd
